export const FETCH_SCENARIOS = 'FETCH_SCENARIOS';
export const FETCH_SCENARIO = 'FETCH_SCENARIO';
export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const EDIT_SCENARIO = 'EDIT_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';

export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const EDIT_CHARACTER = 'EDIT_CHARACTER';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';

export const FETCH_ALIGNMENTS = 'FETCH_ALIGNMENTS';
export const FETCH_RACES = 'FETCH_RACES';
export const FETCH_CLASSES = 'FETCH_CLASSES';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';