export const FETCH_SCENARIOS = 'FETCH_SCENARIOS';
export const FETCH_SCENARIO = 'FETCH_SCENARIO';
export const CREATE_SCENARIO = 'CREATE_SCENARIO';
export const EDIT_SCENARIO = 'EDIT_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';

export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const CREATE_CHARACTER = 'CREATE_CHARACTER';
export const EDIT_CHARACTER = 'EDIT_CHARACTER';
